services:
  rneateam:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - db-data:/app/data
    env_file:
      - .env
    environment:
      - ORIGIN=https://rnea.erkut.dev
      - TURSO_CONNECTION_URL=file:/app/data/local.db
      - TURSO_AUTH_TOKEN=unused
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:3000'
      interval: 2s
      timeout: 10s
      retries: 15

volumes:
  db-data:
